services:
    database:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: neltech
        ports:
        - "3306:3306"
        volumes:
            - ./db-vol:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
        ports:
        - "3307:80"
        depends_on:
        - database

volumes:
    database:
